#define HIRZEL_DATA_I
#include <hirzel/data.h>
#define HIRZEL_PLUGIN_I
#include <hirzel/plugin.h>
#define HIRZEL_UTIL_SYS_I
#include <hirzel/util/sys.h>
#define HIRZEL_UTIL_STR_I
#include <hirzel/util/str.h>
#define HIRZEL_UTIL_FILE_I
#include <hirzel/util/file.h>
#define HIRZEL_LOGGER_I
#include <hirzel/logger.h>
